### ISSUE TITLE
Milestone 1: Login page and registration page [2pt]

### ISSUE THREAD

**Issue by MargaretTechworld** [MargaretTechworld/recipe-app#3]
- [ ] Can register a new user.
- [ ] User logs in with a combination of email and password.
- [ ] Hashed password should be stored in the database.
- [ ] Ask for confirmation of email.
- [ ] Can reset password.
